name: CI

on:
  pull_request:
  push:
    branches: [develop, main]

concurrency:
  group: ci-${{ github.ref }}-group
  cancel-in-progress: true

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - name: Setup DB
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '15.1'
          postgresql db: school_management
          postgresql user: learning
          postgresql password: sa123456
      - name: Pull repository
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
      - name: Build Jar file
        run: ./project-dev build-jar
      - name: Save Jar file
        uses: actions/upload-artifact@v3
        with:
          name: demo-0.0.1-SNAPSHOT
          path: target/demo-0.0.1-SNAPSHOT.jar
          retention-days: 1
      - name: Generate report file
        run: ./project-dev prepare-report
      - name: Save generated report file
        uses: actions/upload-artifact@v3
        with:
          name: report-file
          path: dist/demo-report.tar.gz
          retention-days: 1
      - name: Generate coverage report
        run: ./project-dev test-coverage-report
      - name: Save coverage report
        uses: actions/upload-artifact@v3
        with:
          name: unit-test-coverage-report
          path: target/site/jacoco/index.html
          retention-days: 1
      - name: Run unit tests
        run: mvn test
